name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Setup Project and build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm ci
    - name: Upload Artifacts 1/4
      uses: actions/upload-artifact@v3.1.1
      with:
          name: AppImage
          path: dist/*.AppImage
    - name: Upload Artifacts 2/4
      uses: actions/upload-artifact@v3.1.1
      with:
          name: Snap
          path: dist/*.snap
    - name: Upload Artifacts 3/4
      uses: actions/upload-artifact@v3.1.1
      with:
          name: DEB
          path: dist/*.deb
    - name: Upload Artifacts 4/4
      uses: actions/upload-artifact@v3.1.1
      with:
          name: RPM
          path: dist/*.rpm
